package com.heim.flowlayout;

import java.util.List;

/**
 * Created by zxp on 2016/7/14 0014.
 */
public class DataCenter {
    public static void addData(List data) {
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");
        data.add("小说");
        data.add("斗地主");
        data.add("优酷");
        data.add("网游");
        data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");
        data.add("小说");
        data.add("斗地主");
        data.add("优酷");
        data.add("网游");
        data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");
        data.add("小说");
        data.add("斗地主");
        data.add("优酷");
        data.add("网游");
        data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");
        data.add("小说");
        data.add("斗地主");
        data.add("优酷");
        data.add("网游");
        data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");   data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");   data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");   data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");   data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机"); data.add("WIFI万能钥匙");
        data.add("播放器");
        data.add("QQ");
        data.add("视频");
        data.add("放开那三国");
        data.add("电子书");
        data.add("酒店");
        data.add("单机");
    }
}
